import { UserInterface } from "../pages/Users/UserList";

export const users: UserInterface[] = [
  {
    id: "1",
    name: "Rama",
    role: "Admin",
    email: "ram@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
  {
    id: "2",
    name: "Shyam",
    role: "User",
    email: "shy@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
  {
    id: "3",
    name: "Rama",
    role: "User",
    email: "ram@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
  {
    id: "4",
    name: "Jady",
    role: "User",
    email: "jady@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
  {
    id: "5",
    name: "Madhu",
    role: "User",
    email: "madhu@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
  {
    id: "6",
    name: "Kakadia",
    role: "User",
    email: "ram@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
  {
    id: "7",
    name: "Rama",
    role: "User",
    email: "ram@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
  {
    id: "8",
    name: "Rama",
    role: "User",
    email: "ram@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
  {
    id: "9",
    name: "Rama",
    role: "User",
    email: "ram@gmail.com",
    phone: "9066801445",
    status: "Active",
  },
];
